#!/usr/bin/env bash
# Write a Bash script that configures a server to the above requirements (debug task)
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
